Repository frc-862/rhapsody, pull requests merged in 2024-01, with the labels that each got.

#14 [#5][#9] Added CTRE Swerve
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/Telemetry.java
  src/main/java/frc/robot/subsystems/Swerve.java
  src/main/java/frc/robot/subsystems/templateSubsystem.java
Labels: feature, drivetrain

#15 [#12] Created basic collector with beambreak
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: collector

#19 [#17] Delete template subsystems
  src/main/java/frc/robot/command/template.java
  src/main/java/frc/robot/subsystems/templateSubsystem.java
Labels: cleanup

#25 11 basic shooter
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Shoot.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/ShooterTargeting.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, shooter

#34 [#31] Added two sided collector + Collect default command
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/RunCollectorOnBeamBreak.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: collector, cleanup

#47 [#13] - point to tags
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, drivetrain, vision

#57 [#56] Got new offsets
  src/main/java/frc/robot/Constants.java
Labels: drivetrain

#53 [#32] - renamed angle function in pivot
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: cleanup

#55 [#44] - added lock on command and heading PID constant
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: feature, drivetrain

#62 [#54] display slow mode
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug, documentation, drivetrain

#71 [#37] test initial autons
  src/main/deploy/pathplanner/paths/4-ST-[C1-C2-C3]-RF.path
Labels: auton, testing

#80 [#78] pathplanner dep
  vendordeps/PathplannerLib.json
Labels: documentation

#75 [#72] cleaned collector, switched to top bottom
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: documentation, collector, cleanup

#63 [#60] add state machine switching
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/Shoot.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Collision.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/Shooter.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: shooter

#77 [#49] move and angel
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: feature, drivetrain, vision

#82 [#73] - Added individual control to flywheel motors
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: shooter

#90 [#89] Modified Can bus constants
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug

#93 [#92] New Constants
  src/main/java/frc/robot/Constants.java
Labels: drivetrain

#106 [#105] - removed collision subsystem
  src/main/java/frc/robot/subsystems/Collision.java
Labels: cleanup

#98 [#79] note align
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: drivetrain, vision, auton

#103 [#101] - added more logging to commands/subsystems
  src/main/java/frc/robot/command/Climb.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/ManualClimb.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: logging

#109 Use the timestamp now stored in Pose4d (be sure and update Thunder first)
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug, drivetrain

#114 [#108] chase pieces
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: drivetrain, vision, auton

#113 [#104] create basic leds
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SetLED.java
  src/main/java/frc/robot/command/SwirlLEDs.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: feature

#119 [#118] change drive system test to robot relative
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/tests/DriveTest.java
  src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
  src/main/java/frc/robot/command/tests/TurnSystemTest.java
Labels: drivetrain, system tests

#128 [#121] enable linter to be run manually
  .github/linter_suppressions.xml
  .github/linter_suppressions_limited.xml
  .github/sun_checks.xml
  .github/workflows/gradle.yml
  .github/workflows/linter.yml
Labels: meta

#129 99 shoot system tests
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/tests/testCommands/CollectorTest.java
  src/main/java/frc/robot/command/tests/testCommands/FlywheelTest.java
  src/main/java/frc/robot/command/tests/testCommands/IndexerTest.java
  src/main/java/frc/robot/command/tests/testCommands/PivotTest.java
Labels: shooter, indexer, system tests

#134 112 climb system tests
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/tests/ClimbSystemTest.java
  src/main/java/frc/robot/command/tests/testCommands/ClimbTest.java
Labels: climber, system tests

#125 [#122] Added Linked-points
  src/main/deploy/pathplanner/autos/SM-3.auto
  src/main/deploy/pathplanner/paths/1MeterSquareLL.path
  src/main/deploy/pathplanner/paths/Linked points.path
  src/main/deploy/pathplanner/paths/Run_Through_Pieces.path
  src/main/deploy/pathplanner/paths/StraightOut.path
Labels: auton
