Repository frc-862/rhapsody, pull requests merged in 2024-04, with the labels that each got.

#529 [#526] fix auto smart collect
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/AutonSmartCollect.java
Labels: collector, auton

#538 [#537] Dependabot Milestone
  .github/dependabot.yml
Labels: meta

#540 [#534] note pass w interp map
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/NotePass.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature
