Repository frc-862/rhapsody, pull requests merged in 2024-02, with the labels that each got.

#144 131 make led commands
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/LEDCommands.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: LED

#153 [#152] Made index command
  src/main/java/frc/robot/command/Index.java
Labels: indexer

#154 [#48] signal logger
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: logging

#155 [#150] configured button bindings for now
  src/main/java/frc/robot/RobotContainer.java
Labels: documentation, cleanup

#170 [#138] - tuned the heading controller
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
Labels: drivetrain, vision

#173 [#149] fixed blink
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: LED

#174 [#162] - added an enum and states for cand shots
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Shooter.java
Labels: feature, shooter

#177 171 - test chase piece
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: drivetrain, vision

#175 [#167] added haptic command
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/HapticFeedback.java
Labels: feature

#179 [#163] cand shot state button bindings
  src/main/java/frc/robot/RobotContainer.java
Labels: feature, shooter

#186 [#178] sing
  src/main/deploy/bohemianrhapsody.chrp
  src/main/deploy/jeopardy.chrp
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Climb.java
  src/main/java/frc/robot/command/HapticFeedback.java
  src/main/java/frc/robot/command/Sing.java
  src/main/java/frc/robot/command/tests/SingSystemTest.java
Labels: feature

#194 [#193] - clean point at tags
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: drivetrain, cleanup

#197 [#180] Limelight names
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Limelights.java
Labels: documentation, vision

#198 [#165] Shooter biases
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Pivot.java
Labels: feature, shooter

#203 [#202] Moved isTipped
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: drivetrain, cleanup

#205 [#204] changed the limelight names
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/subsystems/Limelights.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug

#207 182 week 0 controls
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: documentation, feature

#206 [#183] modify climb
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Climb.java
  src/main/java/frc/robot/command/ManualClimb.java
  src/main/java/frc/robot/command/TipDetection.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: cleanup, climber

#209 [#191] implement leds
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Climb.java
  src/main/java/frc/robot/command/SetLEDState.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: LED

#216 [#212] added shoot and collect named commands
  src/main/java/frc/robot/RobotContainer.java
Labels: auton, LED

#215 [#176] - stabilized chase pieces
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ChasePieces.java
Labels: drivetrain, vision, auton

#211 [#38] pathfinding
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/tests/testCommands/ClimbTest.java
Labels: feature, drivetrain, auton

#217 [#200] - add more songs and motors
  src/main/deploy/anotheronebitesthedust.chrp
  src/main/deploy/bewaretheforestmushrooms.chrp
  src/main/deploy/crazylittlethingcalledlove.chrp
  src/main/deploy/encounter.chrp
  src/main/deploy/nationalpark.chrp
  src/main/deploy/piratesofthecaribbean.chrp
  src/main/deploy/sweetcaroline.chrp
  src/main/deploy/underpressure.chrp
  src/main/deploy/wearethechampions.chrp
  src/main/deploy/wiisports.chrp
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Sing.java
  src/main/java/frc/robot/command/tests/SingSystemTest.java
Labels: feature, system tests

#226 [#225][#123] Update Vendor dep
  src/main/java/frc/robot/RobotContainer.java
  vendordeps/Phoenix6.json
Labels: meta

#230 [#229] added led collecting state
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: LED

#232 [#220] - removed 3 songs
  src/main/deploy/bewaretheforestmushrooms.chrp
  src/main/deploy/encounter.chrp
  src/main/deploy/nationalpark.chrp
Labels: cleanup, good first Issue

#235 [#218] made functioning robot centric and slow mode button bindings
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug, drivetrain

#228 [#227] Update README.md
  README.md
Labels: meta

#238 [#223] - get pivot gear ratio
  src/main/java/frc/robot/Constants.java
Labels: shooter

#231 [#132] make test 4 piece
  .pathplanner/settings.json
  src/main/deploy/pathplanner/autos/1MeterSquareLL.auto
  src/main/deploy/pathplanner/autos/5-Piece-Div.auto
  src/main/deploy/pathplanner/autos/5piece.auto
  src/main/deploy/pathplanner/autos/SM-3.auto
  src/main/deploy/pathplanner/autos/Spin Square.auto
  src/main/deploy/pathplanner/autos/Spin.auto
  src/main/deploy/pathplanner/autos/TestNamedCommands.auto
  src/main/deploy/pathplanner/autos/Through_Pieces.auto
  src/main/deploy/pathplanner/paths/1MeterSquareLL.path
  src/main/deploy/pathplanner/paths/5Piece.path
  src/main/deploy/pathplanner/paths/BB-C2.path
  src/main/deploy/pathplanner/paths/BF-C2.path
  src/main/deploy/pathplanner/paths/C1-C2.path
  src/main/deploy/pathplanner/paths/C1-F1.path
  src/main/deploy/pathplanner/paths/C1-F2.path
  src/main/deploy/pathplanner/paths/C1-F3.path
  src/main/deploy/pathplanner/paths/C2-C1.path
  src/main/deploy/pathplanner/paths/C2-C3.path
  src/main/deploy/pathplanner/paths/C2-F1.path
  src/main/deploy/pathplanner/paths/C2-F2.path
  src/main/deploy/pathplanner/paths/C2-F3.path
  src/main/deploy/pathplanner/paths/C3-C2.path
  src/main/deploy/pathplanner/paths/Linked points.path
  src/main/deploy/pathplanner/paths/SB-C2.path
  src/main/deploy/pathplanner/paths/SB-C3.path
  src/main/deploy/pathplanner/paths/SM-C2.path
  src/main/deploy/pathplanner/paths/ST-C1.path
  src/main/deploy/pathplanner/paths/T-C2.path
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: feature, auton, testing

#241 [#240] Cleanup systests
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/tests/ClimbSystemTest.java
  src/main/java/frc/robot/command/tests/CollectorSystemTest.java
  src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
  src/main/java/frc/robot/command/tests/FlywheelSystemTest.java
  src/main/java/frc/robot/command/tests/IndexerSystemTest.java
  src/main/java/frc/robot/command/tests/PivotSystemTest.java
  src/main/java/frc/robot/command/tests/SingSystemTest.java
  src/main/java/frc/robot/command/tests/TurnSystemTest.java
  src/main/java/frc/robot/command/tests/testcmds/ClimbTest.java
  src/main/java/frc/robot/command/tests/testcmds/CollectorTest.java
  src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
  src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
  src/main/java/frc/robot/command/tests/testcmds/IndexerTest.java
  src/main/java/frc/robot/command/tests/testcmds/PivotTest.java
  src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
Labels: system tests

#237 [#210] add collect logic
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/command/UpdatePieceState.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: feature, collector, indexer

#249 [#247] changed the CAN constants
  src/main/java/frc/robot/Constants.java
Labels: documentation, cleanup

#261 [#252] move slow mode to swerve
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
  src/main/java/frc/robot/command/tests/TurnSystemTest.java
  src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
  src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, drivetrain, testing

#257 [#244] - vision standard deviation
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: vision, testing

#267 [#254] - cleaned up chase pieces and adjusted for new code
  src/main/java/frc/robot/command/ChasePieces.java
Labels: cleanup

#265 Move limelight read to separate thread for pose updates
  src/main/java/frc/robot/subsystems/Limelights.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: vision

#270 269 update drivetrain request function
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: drivetrain

#266 [#259] - made every logger (that can) use suppliers
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/Climb.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/CandC1.java
  src/main/java/frc/robot/command/shoot/CandC2.java
  src/main/java/frc/robot/command/shoot/CandC3.java
  src/main/java/frc/robot/command/shoot/CandLine.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/Stow.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: cleanup, logging

#288 [#286] Offset and Angles
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, shooter

#294 [#293] fix leds
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: bug, LED

#297 [#296] Fixed main + Removed Nervo
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: cleanup

#298 [#161] Make mobility autons
  src/main/deploy/pathplanner/autos/1-BF-Mobility.auto
  src/main/deploy/pathplanner/autos/1-TF-Mobility.auto
  src/main/deploy/pathplanner/paths/SB-BL.path
  src/main/deploy/pathplanner/paths/ST-TL.path
  src/main/deploy/pathplanner/paths/TF-ST.path
Labels: feature, auton

#300 [#296] Remove nervo (again)
  src/main/java/frc/robot/subsystems/Nervo.java
Labels: cleanup

#299 [#276] test smartcollect & linter fixes
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/Telemetry.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/ManualClimb.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/command/UpdatePieceState.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/CandC1.java
  src/main/java/frc/robot/command/shoot/CandC2.java
  src/main/java/frc/robot/command/shoot/CandC3.java
  src/main/java/frc/robot/command/shoot/CandLine.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/Stow.java
  src/main/java/frc/robot/command/tests/ClimbSystemTest.java
  src/main/java/frc/robot/command/tests/CollectorSystemTest.java
  src/main/java/frc/robot/command/tests/DrivetrainSystemTest.java
  src/main/java/frc/robot/command/tests/FlywheelSystemTest.java
  src/main/java/frc/robot/command/tests/IndexerSystemTest.java
  src/main/java/frc/robot/command/tests/PivotSystemTest.java
  src/main/java/frc/robot/command/tests/SingSystemTest.java
  src/main/java/frc/robot/command/tests/TurnSystemTest.java
  src/main/java/frc/robot/command/tests/testcmds/ClimbTest.java
  src/main/java/frc/robot/command/tests/testcmds/CollectorTest.java
  src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
  src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
  src/main/java/frc/robot/command/tests/testcmds/IndexerTest.java
  src/main/java/frc/robot/command/tests/testcmds/PivotTest.java
  src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: collector, cleanup, testing, indexer

#303 [#302] Fix driver input
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, drivetrain

#304 [#273] - pivot pid
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/subsystems/Pivot.java
Labels: feature, shooter

#309 [#308] update leds
  src/main/java/frc/robot/subsystems/LEDs.java
Labels: LED

#311 [#275] flywheel
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/CandC1.java
  src/main/java/frc/robot/command/shoot/CandC2.java
  src/main/java/frc/robot/command/shoot/CandC3.java
  src/main/java/frc/robot/command/shoot/CandLine.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/Stow.java
  src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, shooter

#316 [#315] New version will test on robot
  build.gradle
Labels: meta

#314 [#305] Smart Collect logic
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SmartCollect.java
Labels: collector, indexer

#317 [#168] amp score position
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SourceCollect.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: feature, shooter

#323 [#164] Working point blank, and tuning
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
Labels: feature, shooter

#322 [#48] temp disable logger
  src/main/java/frc/robot/RobotContainer.java
Labels: logging

#327 [#325] - reverted point blank
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
Labels: shooter, testing

#326 [#310] led blink on startup
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: LED

#337 [#336] - fixed pivot PID
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Pivot.java
Labels: bug, cleanup

#340 [#335] Tuned KV no Kp
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: feature, shooter
