Repository frc-862/rhapsody, pull requests merged in 2024-03, with the labels that each got.

#345 [#260] - point at tag fixes
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtPoint.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: bug, drivetrain, vision

#349 [#341] collector use velocity voltage
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Collector.java
Labels: feature, collector

#350 [#151] actual collision detection
  networktables.json
  simgui-ds.json
  simgui.json
  src/main/deploy/pathplanner/paths/BB-F4.path
  src/main/deploy/pathplanner/paths/BB-F5.path
  src/main/deploy/pathplanner/paths/BF-F4.path
  src/main/deploy/pathplanner/paths/BF-F5.path
  src/main/deploy/pathplanner/paths/BL-F5.path
  src/main/deploy/pathplanner/paths/C1-F1.path
  src/main/deploy/pathplanner/paths/C2-F1.path
  src/main/deploy/pathplanner/paths/C3-F1.path
  src/main/deploy/pathplanner/paths/F1-TL.path
  src/main/deploy/pathplanner/paths/F4-BL.path
  src/main/deploy/pathplanner/paths/F4-TL.path
  src/main/deploy/pathplanner/paths/F5-BL.path
  src/main/deploy/pathplanner/paths/Linked points.path
  src/main/deploy/pathplanner/paths/SB-F4.path
  src/main/deploy/pathplanner/paths/SB-F5.path
  src/main/deploy/pathplanner/paths/TL-F1.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/CollisionDetection.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, drivetrain

#359 [#356] - end smart collect for chase pieces
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/subsystems/Pivot.java
Labels: bug, collector

#362 [#360] interpolation tune
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/SourceCollect.java
  src/main/java/frc/robot/command/shoot/Tune.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: feature, shooter

#361 [#312] systest check
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/Index.java
  src/main/java/frc/robot/command/PointAtPoint.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/tests/ClimbSystemTest.java
  src/main/java/frc/robot/command/tests/CollectorSystemTest.java
  src/main/java/frc/robot/command/tests/CycleSytemTest.java
  src/main/java/frc/robot/command/tests/FlywheelSystemTest.java
  src/main/java/frc/robot/command/tests/IndexerSystemTest.java
  src/main/java/frc/robot/command/tests/PivotAngleTest.java
  src/main/java/frc/robot/command/tests/PivotSystemTest.java
  src/main/java/frc/robot/command/tests/TurnSystemTest.java
  src/main/java/frc/robot/command/tests/testcmds/ClimbTest.java
  src/main/java/frc/robot/command/tests/testcmds/CollectorTest.java
  src/main/java/frc/robot/command/tests/testcmds/DriveTest.java
  src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
  src/main/java/frc/robot/command/tests/testcmds/IndexerTest.java
  src/main/java/frc/robot/command/tests/testcmds/TurnTest.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: cleanup, system tests

#369 332 test named commands
  src/main/deploy/pathplanner/autos/test hee hee.auto
  src/main/deploy/pathplanner/paths/Move Back.path
  src/main/deploy/pathplanner/paths/Move Forward.path
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
  src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/SourceCollect.java
  src/main/java/frc/robot/command/shoot/Stow.java
  src/main/java/frc/robot/command/tests/IndexerSystemTest.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: bug, auton

#368 [#366] added flywheel stop
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: bug, collector

#370 [#364] Tune
  src/main/java/frc/robot/Constants.java
Labels: shooter, testing

#372 [#371] created the collect and go command
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/CollectAndGo.java
Labels: feature, collector, auton

#377 [#339] add rumble to smartcollect
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SmartCollect.java
Labels: collector

#379 [#376] Tube shooter
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/shoot/Tune.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: feature, shooter

#374 [#373] create collectednote
  .gitignore
  src/main/java/frc/robot/command/CollectedNote.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/PointAtPoint.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: feature, collector, auton

#385 [#338] more amp score methods
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/Tune.java
Labels: shooter, testing

#388 [#181] - podium score position
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: shooter, testing

#390 [#383] Add reverse flywheel collect logic
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/command/tests/CycleSytemTest.java
Labels: collector

#399 Point at point always blue
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtPoint.java
Labels: drivetrain

#403 [#401] changed the names (literally just used f2 lol)
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
  src/main/java/frc/robot/command/shoot/Tune.java
  src/main/java/frc/robot/command/tests/testcmds/FlywheelTest.java
  src/main/java/frc/robot/subsystems/Flywheel.java
Labels: cleanup

#402 [#400] fixed distanceToTarget()
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug

#407 [#406] added a few things to help point at point in auton (needs testing)
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/PointAtPoint.java
Labels: bug, auton

#405 [#404] no buzz in auton!
  src/main/java/frc/robot/RobotContainer.java
Labels: auton

#409 [#408] added debouncers for entry and exit beambreaks in indexer
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: bug, collector, indexer

#415 [#414] - commented out ramp rate
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: bug

#420 [#419] fixed the spelling mistake :)
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: cleanup

#418 [#412] rhapsody flywheel
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Pivot.java
Labels: shooter

#427 [#424] Mercury vs Rhapsody pivot
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
  src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
  src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
  src/main/java/frc/robot/command/shoot/PodiumShot.java
  src/main/java/frc/robot/command/shoot/PointBlankShot.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/SourceCollect.java
  src/main/java/frc/robot/command/shoot/Stow.java
  src/main/java/frc/robot/command/shoot/Tune.java
  src/main/java/frc/robot/command/tests/PivotAngleTest.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/PivotMercury.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
Labels: bug, shooter

#430 [#425] - auton chase
  src/main/deploy/pathplanner/autos/Test Chase Auton.auto
  src/main/deploy/pathplanner/paths/New New Path.path
  src/main/deploy/pathplanner/paths/New Path.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
Labels: collector, auton

#433 [#432] made champs be monitored for pose updating
  src/main/java/frc/robot/subsystems/Limelights.java
Labels: bug

#434 [#363] loop overrun
  src/main/deploy/pathplanner/autos/1-BF-Mobility.auto
  src/main/deploy/pathplanner/autos/1-TF-Mobility.auto
  src/main/deploy/pathplanner/autos/1-TF-[F1].auto
  src/main/deploy/pathplanner/autos/5-Piece.auto
  src/main/deploy/pathplanner/autos/Red1.auto
  src/main/deploy/pathplanner/autos/Test Chase Auton.auto
  src/main/deploy/pathplanner/autos/Test-Point-At-Point.auto
  src/main/deploy/pathplanner/autos/Testing chase pieces.auto
  src/main/deploy/pathplanner/autos/Testing collect and go.auto
  src/main/deploy/pathplanner/autos/test hee hee.auto
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/Collect.java
  src/main/java/frc/robot/command/CollisionDetection.java
  src/main/java/frc/robot/command/MoveToPose.java
  src/main/java/frc/robot/command/PointAtPoint.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/Tune.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/PivotMercury.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: logging

#436 [#435] updated maps and beambreak calls
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
Labels: shooter

#429 [#397] update leds
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/SmartClimb.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Limelights.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: LED

#442 [#441] added shuffleboard values for subsystems
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/PivotMercury.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: documentation, cleanup, logging

#447 [#446] Added beambrake loginv
  src/main/deploy/pathplanner/paths/BB-F5.path
  src/main/deploy/pathplanner/paths/BF-F5.path
  src/main/deploy/pathplanner/paths/BL-F5.path
  src/main/deploy/pathplanner/paths/F5-BL.path
  src/main/deploy/pathplanner/paths/Linked points.path
  src/main/deploy/pathplanner/paths/Point At Point Challenge.path
  src/main/deploy/pathplanner/paths/SB-F5.path
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Flywheel.java
  src/main/java/frc/robot/subsystems/Indexer.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
Labels: bug, collector, indexer

#448 [#443] - chase pieces redirection
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/ChasePieces.java
Labels: drivetrain, collector, auton

#451 [#449] did one line so flywheel inverses when indexer goes down
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: shooter, indexer

#455 [#417] climb drift fix
  src/main/java/frc/robot/command/SmartClimb.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: bug, climber

#457 [#391] pivot angle while climbing
  src/main/java/frc/robot/command/SmartClimb.java
Labels: feature, shooter, climber

#456 [#423] climb limit
  src/main/deploy/pathplanner/autos/1-SB-[F4]-EF.auto
  src/main/deploy/pathplanner/autos/4-SB-[C3-C2-C1-F1]-EF.auto
  src/main/deploy/pathplanner/paths/BF-BL.path
  src/main/deploy/pathplanner/paths/BL-F3.path
  src/main/deploy/pathplanner/paths/BL-F4.path
  src/main/deploy/pathplanner/paths/BL-F5.path
  src/main/deploy/pathplanner/paths/C1-F1.path
  src/main/deploy/pathplanner/paths/C2-F1.path
  src/main/deploy/pathplanner/paths/C3-F1.path
  src/main/deploy/pathplanner/paths/F1-TL.path
  src/main/deploy/pathplanner/paths/F3-BL.path
  src/main/deploy/pathplanner/paths/F4-BL.path
  src/main/deploy/pathplanner/paths/F5-BL.path
  src/main/deploy/pathplanner/paths/Linked points.path
  src/main/deploy/pathplanner/paths/SB-BL.path
  src/main/deploy/pathplanner/paths/SF-F1.path
  src/main/deploy/pathplanner/paths/ST-F1.path
  src/main/deploy/pathplanner/paths/TL-F1.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
Labels: feature, climber

#462 [#461] - cleaned up path to pose
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PathToPose.java
Labels: cleanup

#463 445 update leds
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Swerve.java
Labels: LED

#465 [#464] Moved logging
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, logging

#468 [#467] Cleanup
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/Telemetry.java
  src/main/java/frc/robot/command/ChasePieces.java
  src/main/java/frc/robot/command/CollectAndGo.java
  src/main/java/frc/robot/command/PointAtPoint.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/Sing.java
  src/main/java/frc/robot/command/shoot/AutonCand/AmpShotAuton.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC1.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC2.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandC3.java
  src/main/java/frc/robot/command/shoot/AutonCand/CandLine.java
  src/main/java/frc/robot/command/shoot/AutonCand/PointBlankShotAuton.java
  src/main/java/frc/robot/subsystems/LEDs.java
  src/main/java/frc/robot/subsystems/Pivot.java
  src/main/java/frc/robot/subsystems/PivotMercury.java
  src/main/java/frc/robot/subsystems/PivotRhapsody.java
Labels: cleanup

#478 [#473] - faster point at point
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/PointAtPoint.java
Labels: drivetrain, auton

#480 [#472] Retuned and made spot for tuning
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
  src/main/java/frc/robot/command/shoot/preAim.java
Labels: shooter

#474 [#422] climb line up
  src/main/deploy/pathplanner/paths/PathFind-AMP.path
  src/main/deploy/pathplanner/paths/PathFind-CENTER-STAGE.path
  src/main/deploy/pathplanner/paths/PathFind-HIGH-STAGE.path
  src/main/deploy/pathplanner/paths/PathFind-LOW-STAGE.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ClimbAlign.java
  src/main/java/frc/robot/command/ManualClimb.java
  src/main/java/frc/robot/command/PathFindToAuton.java
  src/main/java/frc/robot/command/SmartClimb.java
Labels: feature, drivetrain, climber

#481 [#466] auton collect
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/AutonSmartCollect.java
  src/main/java/frc/robot/command/SmartCollect.java
  src/main/java/frc/robot/subsystems/Collector.java
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: feature, collector, auton

#482 [#476] Encoder Offset
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Climber.java
Labels: shooter

#484 [#483] changed indexerMotor variable to motor
  src/main/java/frc/robot/subsystems/Indexer.java
Labels: cleanup, indexer

#487 [#485] retune shot maps
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/SmartShoot.java
Labels: shooter

#489 [#488] Tuned Amp limit
  src/main/java/frc/robot/Constants.java
Labels: drivetrain

#490 [#486] mercury amp shot
  .github/sun_checks.xml
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/ReverseAmpShot.java
Labels: auton

#492 [#491] Auton point at tag named commands
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/AutonPointAtTag.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/SetStopMePipeline.java
Labels: vision

#498 [#497] changed any calling of deleted the SetStopMePipeline command
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
  src/main/java/frc/robot/command/SetStopMePipeline.java
Labels: cleanup

#499 [#493] clean pipeline calls
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PointAtTag.java
Labels: vision, cleanup

#500 [#495] - combined point commands
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/ComboPoint.java
  src/main/java/frc/robot/command/PointAtPoint.java
Labels: drivetrain, vision

#503 [#501] tune amp
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/ReverseAmpShot.java
Labels: shooter

#505 [#426] - auto line up to amp
  src/main/deploy/pathplanner/paths/BL-F5.path
  src/main/deploy/pathplanner/paths/PathFind-AMP.path
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/PathFindToAuton.java
  src/main/java/frc/robot/command/PathToPose.java
  src/main/java/frc/robot/command/shoot/AmpShot.java
Labels: feature, drivetrain, auton

#509 [#507] - swapped joysticks for climber controls
  src/main/java/frc/robot/RobotContainer.java
Labels: cleanup, climber

#508 [#479] - note pass
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/command/shoot/NotePass.java
Labels: feature, shooter
